name: Deploy project to Reflex Cloud
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          python -m uv pip install reflex
          python -m uv pip install -r requirements.txt
      - name: Create .env file from secret
        run: echo "${{ secrets.REFLEX_ENV_FILE }}" > .env
      
      - name: Build extra args with multiple env variables
        id: build_env_args
        run: |
          ENV_ARGS=""
          while IFS='=' read -r key value; do
            [[ -z "$key" || "$key" =~ ^# ]] && continue
            ENV_ARGS+="--env $key=$value "
          done < .env
          echo "env_args=$ENV_ARGS" >> $GITHUB_OUTPUT
          

      - name: Deploy to Reflex Cloud
        uses: reflex-dev/reflex-deploy-action@v1
        with:
          auth_token: ${{ secrets.REFLEX_AUTH_TOKEN }}
          project_id: ${{ secrets.REFLEX_PROJECT_ID }}
          extra_args: "${{ steps.build_env_args.outputs.env_args }}"
