name: Deploy Reflex to AWS
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
        id-token: write
        contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
            role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
            aws-region: us-east-1
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          python -m uv pip install reflex
          python -m uv pip install -r requirements.txt

      - name: Build Reflex project
        run: |
          reflex init
          # Comandos para empaquetar el proyecto (depende del servicio específico de AWS)
          zip -r deploy.zip . -x "*.git*"

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          application_name: PensionSimulator
          environment_name: PensionSimulator-env
          version_label: "reflex-${{ github.sha }}"
          region: us-east-1
          deployment_package: deploy.zip

