name: Deploy Reflex App

# This workflow deploys a Reflex app to Reflex Cloud when changes are pushed to the main branch.
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug env file
        run: |
          echo "Contenido del archivo production.env:"
          cat production.env

      - name: Deploy to Reflex Cloud
        uses: reflex-dev/reflex-deploy-action@v1
        with:
          auth_token: ${{ secrets.REFLEX_AUTH_TOKEN }}
          project_id: ${{ secrets.REFLEX_PROJECT_ID }}
          extra_args: "--env production.env"

